### ISSUE TITLE
module 'iocextract' has no attribute 'refang_url'

### ISSUE THREAD

**Issue by Bronya-Rayi** [InQuest/ThreatIngestor#143]
config.yml
```yml
general:
    daemon: false
    sleep: 900
    state_path: state.db

sources:
  - name: rsshub-blog
    # Read from the InQuest blog.
    module: rss
    url: https://rsshub.app/twitter/keyword/Gamaredon
    feed_type: messy

operators:
  - name: sqlite-artifacts
    # Write artifacts to a SQLite database.
    module: sqlite
    filename: artifacts.db
```
![image](https://user-images.githubusercontent.com/47048823/233845807-dd41d223-bfad-418c-90fd-db572643693e.png)

![image](https://user-images.githubusercontent.com/47048823/233845905-f795fc74-fc42-4886-8151-538a758384da.png)
