### ISSUE TITLE
Clarify Twitter Credentials

### ISSUE THREAD

**Issue by TacticalCheerio** [InQuest/ThreatIngestor#67]
The Twitter credentials in the config.yml and documentation can be more clear:

Instead of the current

```
- name: twitter-auth
    # https://dev.twitter.com/oauth/overview/application-owner-access-tokens
    token:
    token_key:
    con_secret_key: 
    con_secret: 
```

This would be more clear, as it uses the same terms and order of keys that Twitter presents

```
- name: twitter-auth
    # https://dev.twitter.com/oauth/overview/application-owner-access-tokens
    api_key:
    api_key_secret:
    access_token: 
    access_token_secret: 
```
