### ISSUE TITLE
Ingestion support for Gist streams.

### ISSUE THREAD

**Issue by pedramamini** [InQuest/ThreatIngestor#88]
For example:

https://gist.github.com/silence-is-best

**Comment by Hifumi1337** [comment]
Not a perfect solution, but we now have ingestion support for GitHub gist streams by username. Unfortunately, the API for gists does not offer queries (that I could find), so I found a workaround. Instead of searching for queries, we can use usernames. It shouldn't be too difficult to use something like BS4 as an example or a custom request (`q=`), but this is the quickest method for obtaining gists via the API.

These changes are already merged into `develop` if you're interested in viewing the changes.

Here's an example of the new `config.yml` file:
```yaml
credentials:
  - name: github-auth
    username: USERNAME
    token: TOKEN

sources:
  - name: source-name
    credentials: github-auth
    module: github_gist
    user: QueryUser
```
